---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: bullseye64-coturn
    box: debian/bullseye64
  - name: buster64-coturn
    box: debian/buster64
provisioner:
  name: ansible
  become: yes
